# -*- coding: utf-8 -*-
"""Copy of Tubes ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAvWQdS1tmA3pM1R0RmhUd5GwtzaOfjy
"""

from google.colab import drive
drive.mount('/content/drive')

import os

data_dir = "/content/drive/MyDrive/archive (8)"

print("Isi folder dataset:")
print(os.listdir(data_dir))

import tensorflow as tf

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    image_size=(224, 224),
    batch_size=128,
    label_mode='int',
    shuffle=True
)

class_names = train_ds.class_names
print("Nama kelas:", class_names)

for images, labels in train_ds.take(1):
    for i in range(len(labels)):
        print(labels[i].numpy(), "->", class_names[labels[i].numpy()])

import numpy as np
X = []
y = []

for images, labels in train_ds:
    X.append(images.numpy())
    y.append(labels.numpy())

X = np.concatenate(X, axis=0)
y = np.concatenate(y, axis=0)

import matplotlib.pyplot as plt
from collections import Counter

class_counts = Counter(y)

plt.figure()
plt.bar(class_names, [class_counts[i] for i in range(len(class_names))])
plt.xlabel("Kelas Penyakit Kentang")
plt.ylabel("Jumlah Gambar")
plt.title("Distribusi Jumlah Gambar per Kelas")
plt.show()

r = X[:, :, :, 0].flatten()
g = X[:, :, :, 1].flatten() #plot distribusi intensitas rgb
b = X[:, :, :, 2].flatten()

plt.figure()
plt.hist(r, bins=50, alpha=0.5, label="Red")
plt.hist(g, bins=50, alpha=0.5, label="Green")
plt.hist(b, bins=50, alpha=0.5, label="Blue")
plt.xlabel("Intensitas Pixel")
plt.ylabel("Frekuensi")
plt.title("Distribusi Intensitas RGB (Global)")
plt.legend()
plt.show()

mean_rgb = [] #plot rata-rata rgb per kelas

for i in range(len(class_names)):
    imgs = X[y == i]
    mean_rgb.append(imgs.mean(axis=(0,1,2)))

mean_rgb = np.array(mean_rgb)

plt.figure()
plt.plot(class_names, mean_rgb[:,0], marker='o', label='Red')
plt.plot(class_names, mean_rgb[:,1], marker='o', label='Green')
plt.plot(class_names, mean_rgb[:,2], marker='o', label='Blue')
plt.xlabel("Kelas")
plt.ylabel("Rata-rata Intensitas")
plt.title("Rata-rata RGB per Kelas")
plt.legend()
plt.show()

# Pastikan y adalah 1D integer
y = np.array(y).flatten().astype(int)

# Hitung grayscale per gambar (mean RGB → brightness)
gray_images = X.mean(axis=3)          # shape: (n_samples, height, width)
brightness = gray_images.reshape(len(X), -1).mean(axis=1)  # rata-rata brightness per gambar

# Atau jika ingin semua pixel (lebih detail, tapi lebih berat):
# brightness_all = gray_images.flatten()  # → semua pixel dari semua gambar

# Pisahkan brightness berdasarkan kelas
brightness_per_class = {}
for i, name in enumerate(class_names):
    mask = (y == i)
    brightness_per_class[name] = brightness[mask]   # rata-rata brightness per gambar per kelas

# --- Plot Overlay Histogram ---
plt.figure(figsize=(10, 6))

for name, vals in brightness_per_class.items():
    plt.hist(vals, bins=50, alpha=0.6, label=name, density=True)  # density=True agar normalisasi sama

plt.xlabel("Brightness (Grayscale rata-rata per gambar)")
plt.ylabel("Density (probabilitas relatif)")
plt.title("Distribusi Brightness Citra per Kelas")
plt.legend()
plt.grid(True, alpha=0.3)
plt.xlim(0, 255)  # asumsi range 0-255
plt.show()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y
)

X_test.shape

y_test.shape

plt.imshow(X_train[1].astype("uint8"))
plt.title(class_names[y_train[1]])
plt.axis("off")
plt.show

X_train = X_train/224 #normalisasi
X_test = X_test/224

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Buat ImageDataGenerator dengan augmentasi
datagen = ImageDataGenerator(
    rotation_range=20,        # Rotasi gambar ±20 derajat
    width_shift_range=0.2,    # Geser horizontal ±20%
    height_shift_range=0.2,   # Geser vertikal ±20%
    shear_range=0.2,          # Transformasi shear
    zoom_range=0.2,           # Zoom in/out
    horizontal_flip=True,     # Flip horizontal
    fill_mode='nearest'       # Mode pengisian piksel baru
)

# Fitting jika perlu (biasanya untuk normalization)

train_gen = datagen.flow(X_train, y_train, batch_size=128)

import tensorflow as tf
from tensorflow.keras import models, layers
ann = models.Sequential([
    layers.Flatten(input_shape=(224,224,3)),
    layers.Dense(3000, activation='relu'),
    layers.Dense(1000, activation='relu'),
    layers.Dense(3, activation='softmax')
])

ann.compile(
    optimizer='SGD',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

ann.fit(train_gen, epochs=5)

import seaborn as sns
from sklearn.metrics import confusion_matrix

# 1. Prediksi
y_pred_prob = ann.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# 2. y_true langsung dari y_test
y_true = y_test  # pastikan bentuknya sama (1D integer)

# 3. Cek jumlah sampel
print("Jumlah sampel true :", len(y_true))
print("Jumlah sampel pred :", len(y_pred))
assert len(y_true) == len(y_pred)

# 4. Confusion Matrix
class_names = ['Early Blight', 'Late Blight', 'Healthy']

cm = confusion_matrix(y_true, y_pred)

# Visualisasi seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - ANN Model')
plt.show()

cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(224, 224, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy']) #model cnn

cnn.fit(train_gen,epochs=5) #menghitung akurasi

# 1. Prediksi
y_pred_prob = cnn.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# 2. y_true langsung dari y_test
y_true = y_test  # pastikan bentuknya sama (1D integer)

# 3. Cek jumlah sampel
print("Jumlah sampel true :", len(y_true))
print("Jumlah sampel pred :", len(y_pred))
assert len(y_true) == len(y_pred)

# 4. Confusion Matrix
class_names = ['Early Blight', 'Late Blight', 'Healthy']

cm = confusion_matrix(y_true, y_pred)

# Visualisasi seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - ANN Model')
plt.show()

# 1. Prediksi
y_pred_prob = cnn.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# 2. y_true langsung dari y_test
y_true = y_test  # pastikan bentuknya sama (1D integer)

# 3. Cek jumlah sampel
print("Jumlah sampel true :", len(y_true))
print("Jumlah sampel pred :", len(y_pred))
assert len(y_true) == len(y_pred)

# 4. Confusion Matrix
class_names = ['Early Blight', 'Late Blight', 'Healthy']

cm = confusion_matrix(y_true, y_pred)

# Visualisasi seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - ANN Model')
plt.show()

cnn_non_aug = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(224, 224, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
cnn_non_aug.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 1. Prediksi
y_pred_prob = cnn_non_aug.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# 2. y_true langsung dari y_test
y_true = y_test  # pastikan bentuknya sama (1D integer)

# 3. Cek jumlah sampel
print("Jumlah sampel true :", len(y_true))
print("Jumlah sampel pred :", len(y_pred))
assert len(y_true) == len(y_pred)

# 4. Confusion Matrix
class_names = ['Early Blight', 'Late Blight', 'Healthy']

cm = confusion_matrix(y_true, y_pred)

# Visualisasi seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - ANN Model')
plt.show()

ann_non_aug = models.Sequential([
    layers.Flatten(input_shape=(224,224,3)),
    layers.Dense(3000, activation='relu'),
    layers.Dense(1000, activation='relu'),
    layers.Dense(3, activation='softmax')
])

ann_non_aug.compile(
    optimizer='SGD',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

ann_non_aug.fit(X_train, y_train, epochs=5)

# 1. Prediksi
y_pred_prob = cnn_non_aug.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)

# 2. y_true langsung dari y_test
y_true = y_test  # pastikan bentuknya sama (1D integer)

# 3. Cek jumlah sampel
print("Jumlah sampel true :", len(y_true))
print("Jumlah sampel pred :", len(y_pred))
assert len(y_true) == len(y_pred)

# 4. Confusion Matrix
class_names = ['Early Blight', 'Late Blight', 'Healthy']

cm = confusion_matrix(y_true, y_pred)

# Visualisasi seaborn
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - ANN Model')
plt.show()